com.trekglobal.idempiere.rest.api/META-INF/MANIFEST.MF, com.trekglobal.idempiere.rest.api/OSGI-INF/com.trekglobal.idempiere.rest.api.json.DefaultQueryConverter.xml, com.trekglobal.idempiere.rest.api/build.properties, com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/ConvertedQuery.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/DefaultQueryConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/IQueryConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/IQueryConverterFactory.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/ODataUtils.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/ModelResource.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/FormResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/InfoResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ProcessResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/WindowResourceImpl.java
Implemented partially the filter option from oData, replacing the SQL calls
=>  Filter Improvement, replace WHERE SQL #10 

com.trekglobal.idempiere.rest.api/postman/http---localhost-8080.postman_environment.json, com.trekglobal.idempiere.rest.api/postman/https---test-postgresql.idempiere.org.postman_environment.json, com.trekglobal.idempiere.rest.api/postman/https---test.idempiere.org.postman_environment.json, com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json
Refactor Postman Collection to use Environments
Add environments for localhost, test.idempiere and test-postgresql.idempiere
=> Postman Environments

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java
Implement cross tenant check on foreign keys for insert and update
Avoid cross tenant data insertion #42
https://idempiere.atlassian.net/browse/IDEMPIERE-4268
Depends on https://github.com/idempiere/idempiere/pull/425
=> IDEMPIERE-4268 Web Services : Read miss cross-tenant check

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java
Xref: https://mattermost.idempiere.org/idempiere/pl/iqikb6g88ind3x3pnyefzsc1fo
=> Respect the iDempiere columnname syntax when creating the response

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultGridTabSerializer.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/Process.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ProcessResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/info/InfoWindow.java
Increase the scope to other points to always write the response with columnnames
Adapt to try converted and original when reading
=> Respect the iDempiere columnname syntax when creating the response #48

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java
Added System SysConfig for using lower case ColumnNames. 
Adding System Sysconfig **REST_COLUMNNAME_TOLOWERCASE** we can use lowercase column names.
=> Added SysConfig for ColumnName

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ProcessResourceImpl.java
https://idempiere.atlassian.net/browse/IDEMPIERE-4678
This requires first the pull request https://github.com/idempiere/idempiere/pull/559 to be integrated.
=> IDEMPIERE-4678 Save log informing Notice created when background job

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/impl/AuthServiceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/CacheResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/FormResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/InfoResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/NodeResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ProcessResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ReferenceResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ServerResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/WindowResourceImpl.java
* Replace all array responses embedding the array within a JSON object
=> Issue #63 Recommended practice is to always return a JSON object

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java
As suggested by @CarlosRuiz-globalqss in mattermost channel, this pull request fixes the issue #95
=> fix default value when a record is created by REST #95

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java
Implemented afterSave event and a property event isNew, to indicate if the record isNew (when event is dispatched by ModelResourceImpl.java create method, the property is true. When dispatched by update method, the property is false) 
To retrieve isNew property value, in EventHandler class (which extends ModelEventDelegate.java) just do:
boolean isNew = (boolean) getEvent().getProperty("isNew");
=> Implemented afterSave event and isNew event property

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/DefaultQueryConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/ODataUtils.java
=> 2 columns comparison on server side #92

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/filter/RequestFilter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/impl/AuthServiceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/jwt/LoginClaims.java
https://github.com/bxservice/idempiere-rest/issues/104
=> Issue #104 - REST allows login with wrong roleId

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/ImageTypeConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/TypeConverterUtils.java
IDEMPIERE-REST-102 - Implemente Image Type Converter
=> Idempiere rest 102

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/NumericTypeConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/TypeConverterUtils.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/ConvertedQuery.java
Added Support to show value of buttons (mostly Record_ID)
Issue: #8
=> Issue #8 Add Support to show Button column values

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/LookupTypeConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/YesNoTypeConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java
Issue #121:
- Added recursive method to create multiple children
=> Added Improvement About Issue #121: Recursive Method to Create Children Models

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/NumericTypeConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/TypeConverterUtils.java
Issue: #155 
New DisplayType RecordID is Not supported, rest GET always return null, POST/PUT does not update value.
=> Added Record ID Support to TypeConverter #155

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/info/InfoWindow.java
Discovered while testing https://github.com/idempiere/idempiere/pull/1893
=> Fix wrong call to get_ColumnIndex instead of getColumnIndex

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/CacheResourceImpl.java
https://github.com/bxservice/idempiere-rest/issues/161
=> Fix #161 - The response of DEL api/v1/caches is an invalid JSON

com.trekglobal.idempiere.rest.api/keycloak/oidc-test.postman_collection.json
=> Implement #172 Add OIDC access token validation support

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java
=> Issue #202 - Improved security by checking column access per role

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/model/MRefreshToken.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/AuthService.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/LogoutParameters.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/filter/RequestFilter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/impl/AuthServiceImpl.java
- implement logout endpoint closing the session
- request filter fails with Unauthorized error when the session is processed
- delete the previous refresh token when a new one is generated
=> Issue #209 Implement logout endpoint

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/NumericTypeConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/TypeConverterUtils.java
- implement ability to set a column to null
- do not throw error when a column is not updatable but is not being updated
=> PUT/POST must error if column is not updatable #198 / Cannot set a field to null using POST #208

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/impl/AuthServiceImpl.java
- fix issue with expiration when the SysConfig is defined on tenant level
=> Issue #173 Add support for refreshToken

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/DefaultQueryConverter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/ODataUtils.java
The in [array] is not implemented
=>  #188 - Implement IN Operator

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/ApplicationV1.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/ChartResource.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ChartResourceImpl.java
Depends on https://github.com/idempiere/idempiere/pull/2494
=> Implement charts endpoint to get chart images #258

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/ApplicationV1.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/filter/RequestFilter.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/filter/RequestSetLanguageFilter.java
Issue: https://github.com/bxservice/idempiere-rest/issues/263
Added New Filter for setting AD_Language from query parameter key locale.
Added Priority to Request filter to maintain right Filter Order.
=> Added Filter to set Language from query Parameter #263

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/filter/DefaultQueryConverter.java
as reported by @uthadehikaru
at https://mattermost.idempiere.org/idempiere/pl/dhq9txaewiywuxhjhnynerh83o
=> Fix issue with parenthesis in literal #92

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/ChartResource.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ChartResourceImpl.java
Depends on https://github.com/idempiere/idempiere/pull/2579
=> Create charts/data endpoint #276

com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/ApplicationV1.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/TaskResource.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/TaskResourceImpl.java
requires https://github.com/idempiere/idempiere/pull/2624
=> Implement tasks endpoint #297

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/LoginParameters.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/auth/impl/AuthServiceImpl.java
=> Enhance the flexiblity of authentication request #303

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ViewResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/YAMLSchema.java
=> YAML schema improvements #317

com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/DefaultPOSerializer.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ViewResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/YAMLSchema.java
=> Implement value object mapping for REST_View #335

com.trekglobal.idempiere.rest.api.test/pom.xml
=> Unit testing idempiere REST #341

com.trekglobal.idempiere.rest.api.test/src/com/trekglobal/idempiere/rest/api/json/test/ModelHelperTest.java, com.trekglobal.idempiere.rest.api.test/src/com/trekglobal/idempiere/rest/api/json/test/ResponseUtilsTest.java
Added unit tests for ResponseUtils and ModelHelper
=> #341 - Extend unit test coverage

com.trekglobal.idempiere.rest.api/openapi/idempiere-rest.yml, com.trekglobal.idempiere.rest.api/postman/trekglobal-idempiere-rest.postman_collection.json, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/ModelHelper.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/QueryOperators.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/expand/ExpandParser.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/json/expand/ExpandUtils.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/ModelResource.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ModelResourceImpl.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/ViewResourceImpl.java
[Get table data based on labels #352](https://github.com/bxservice/idempiere-rest/issues/352)
[Append label data to retrieved records #353](https://github.com/bxservice/idempiere-rest/issues/353)
Changes:
- Added a new query option: **$label** to serve as a label filter
- Added support for nested **$label** within the **$expand**
- Added a new query option: **showlabel**
Notes:
- **$label** query option is used to filter labels (i.e. AD_Label) within the assigned labels
`/api/v1/models/C_BPartner?$label=Name eq '%23Customer'` to get business partner records where the name of the Assigned Label > Label is '#Customer'.
- By default, **showlabel** query option returns a comma-separated list of assigned label names
`"assigned-labels": "#Customer, #Vendor"`
- **showlabel=list** query option …
=> Get table data based on labels #352

com.trekglobal.idempiere.rest.api/openapi/idempiere-rest.yml
=> Implement bulk/composite request endpoint #379

com.trekglobal.idempiere.rest.api/openapi/idempiere-rest.yml, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/UploadResource.java, com.trekglobal.idempiere.rest.api/src/com/trekglobal/idempiere/rest/api/v1/resource/impl/UploadResourceImpl.java
- Fix DEL request (cancel upload)
=> Refinement of v1/uploads endpoint #377
